##位码
set_property PACKAGE_PIN G6 [get_ports {wm1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[0]}]
set_property PACKAGE_PIN E1 [get_ports {wm1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[1]}]
set_property PACKAGE_PIN F1 [get_ports {wm1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[2]}]
set_property PACKAGE_PIN G1 [get_ports {wm1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[3]}]
##时钟
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk ]
##段码
set_property PACKAGE_PIN H2 [get_ports {dm1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[0]}]
set_property PACKAGE_PIN D2 [get_ports {dm1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[1]}]
set_property PACKAGE_PIN E2 [get_ports {dm1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[2]}]
set_property PACKAGE_PIN F3 [get_ports {dm1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[3]}]
set_property PACKAGE_PIN F4 [get_ports {dm1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[4]}]
set_property PACKAGE_PIN D3 [get_ports {dm1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[5]}]
set_property PACKAGE_PIN E3 [get_ports {dm1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[6]}]
set_property PACKAGE_PIN D4 [get_ports {dm1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[7]}]
##开关
set_property PACKAGE_PIN R1 [get_ports {a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
set_property PACKAGE_PIN N4 [get_ports {a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]
set_property PACKAGE_PIN M4 [get_ports {a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[2]}]
##计数开关
set_property PACKAGE_PIN R15 [get_ports s]
set_property IOSTANDARD LVCMOS33 [get_ports s]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {s_IBUF}]

#存的数
set_property PACKAGE_PIN P2 [get_ports {t[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {t[0]}]
set_property PACKAGE_PIN p3 [get_ports {t[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {t[1]}]
set_property PACKAGE_PIN P4 [get_ports {t[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {t[2]}]
set_property PACKAGE_PIN P5 [get_ports {t[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {t[3]}]