set_property PACKAGE_PIN G6 [get_ports {dm[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[0]}]

##set_property PACKAGE_PIN G6 [get_ports {dm[0]}]
##set_property IOSTANDARD LVCMOS33 [get_ports {dm[0]}]
set_property PACKAGE_PIN E1 [get_ports {dm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[1]}]
set_property PACKAGE_PIN F1 [get_ports {dm[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[2]}]
set_property PACKAGE_PIN G1 [get_ports {dm[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[3]}]

set_property PACKAGE_PIN H2 [get_ports {num[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[0]}]
set_property PACKAGE_PIN D2 [get_ports {num[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[1]}]
set_property PACKAGE_PIN E2 [get_ports {num[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[2]}]
set_property PACKAGE_PIN F3 [get_ports {num[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[3]}]
set_property PACKAGE_PIN F4 [get_ports {num[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[4]}]
set_property PACKAGE_PIN D3 [get_ports {num[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[5]}]
set_property PACKAGE_PIN E3 [get_ports {num[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[6]}]
set_property PACKAGE_PIN D4 [get_ports {num[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[7]}]

set_property PACKAGE_PIN P17 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
