# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VProject/Carlight/Carlight.srcs/sources_1/ip/divClk_0/divClk_0.xci
# IP: The module: 'divClk_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VProject/Carlight/Carlight.gen/sources_1/ip/divClk_0/constrs_1/new/con_divClk.xdc
# XDC: The top module name and the constraint reference have the same name: 'divClk_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/VProject/Carlight/Carlight.srcs/sources_1/ip/divClk_0/divClk_0.xci
# IP: The module: 'divClk_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VProject/Carlight/Carlight.gen/sources_1/ip/divClk_0/constrs_1/new/con_divClk.xdc
# XDC: The top module name and the constraint reference have the same name: 'divClk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
