#!/bin/bash
echo "test1"
./parser ./test/test1.cmm
echo "test2"
./parser ./test/test2.cmm
echo "test3"
./parser ./test/test3.cmm
echo "test4"
./parser ./test/test4.cmm
echo "test5"
./parser ./test/test5.cmm
echo "test6"
./parser ./test/test6.cmm
echo "test7"
./parser ./test/test7.cmm
echo "test8"
./parser ./test/test8.cmm
echo "test9"
./parser ./test/test9.cmm
echo "test10"
./parser ./test/test10.cmm
echo "test11"
./parser ./test/test11.cmm
echo "test12"
./parser ./test/test12.cmm
echo "test13"
./parser ./test/test13.cmm
echo "test14"
./parser ./test/test14.cmm
echo "test15"
./parser ./test/test15.cmm
echo "test16"
./parser ./test/test16.cmm
echo "test17"
./parser ./test/test17.cmm
