##时钟
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
##开关
set_property PACKAGE_PIN P5 [get_ports s3]
set_property IOSTANDARD LVCMOS33 [get_ports s3]
set_property PACKAGE_PIN P4 [get_ports s2]
set_property IOSTANDARD LVCMOS33 [get_ports s2]
set_property PACKAGE_PIN P3 [get_ports s1]
set_property IOSTANDARD LVCMOS33 [get_ports s1]
##按钮
set_property PACKAGE_PIN R15 [get_ports switch]
set_property IOSTANDARD LVCMOS33 [get_ports switch]
set_property PACKAGE_PIN U4 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports up]
##set_property PACKAGE_PIN R17 [get_ports down]
##set_property IOSTANDARD LVCMOS33 [get_ports down]
##LED
set_property PACKAGE_PIN F6 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN G4 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN G3 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN J4 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN H4 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN J3 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN J2 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN K2 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
##AUDIO_PWM
set_property PACKAGE_PIN T1 [get_ports AUDIO_PWM]
set_property IOSTANDARD LVCMOS33 [get_ports AUDIO_PWM]
##AUDIO_SD
set_property PACKAGE_PIN M6 [get_ports AUDIO_SD]
set_property IOSTANDARD LVCMOS33 [get_ports AUDIO_SD]
##位码
set_property PACKAGE_PIN G6 [get_ports {wm1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[0]}]
set_property PACKAGE_PIN E1 [get_ports {wm1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[1]}]
set_property PACKAGE_PIN F1 [get_ports {wm1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[2]}]
set_property PACKAGE_PIN G1 [get_ports {wm1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[3]}]
##段码
set_property PACKAGE_PIN H2 [get_ports {dm1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[0]}]
set_property PACKAGE_PIN D2 [get_ports {dm1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[1]}]
set_property PACKAGE_PIN E2 [get_ports {dm1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[2]}]
set_property PACKAGE_PIN F3 [get_ports {dm1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[3]}]
set_property PACKAGE_PIN F4 [get_ports {dm1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[4]}]
set_property PACKAGE_PIN D3 [get_ports {dm1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[5]}]
set_property PACKAGE_PIN E3 [get_ports {dm1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[6]}]
set_property PACKAGE_PIN D4 [get_ports {dm1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[7]}]
