# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/con_test.xdc

# IP: ip/mc_0/mc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mc_0 || ORIG_REF_NAME==mc_0} -quiet] -quiet

# IP: ip/divClk_0_1/divClk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divClk_0 || ORIG_REF_NAME==divClk_0} -quiet] -quiet
